### ISSUE TITLE
Cant run test

### ISSUE THREAD

**Issue by bpecsek** [digikar99/numericals#1]
Dear digikar,

I am trying to use numericals but I am facing with a lot of issues.
I can't even run the benchmark since sbcl-numerical package doesn't exist neither d+ d- etc or d2+.
I've planning to play with simd avx2 and sse2 and numericals seemed to be a good option but I am struggling with it.
Do you plan to work on it and make it stable for at least what is implemented.
I wish I contribute but I am not that familiar with simd.

Regards,
Bela

**Comment by digikar99** [comment]
All of this probably requires SBCL-2.0.4.

# sbcl-numericals

PS: This system has been deprecated. The new system is named `numericals`.

Apologies for the broken code. The README is in accordance with [this commit](https://github.com/digikar99/sbcl-numericals/tree/142c47f54512fd1b2a57aa52cd30b52e8181a4e5). So, after you clone - 

```
git clone https://github.com/digikar99/sbcl-numericals.git
git cd sbcl-numericals
git checkout 142c47
```

Then in SLIME: 

```lisp
(asdf:clear-configuration)
;;; You might probably need to add "iterate" to the :depends-on in sbcl-numericals.asd
(ql:quickload :sbcl-numericals.test)
;;; Optionally, check the location with (ql:where-is-system :sbcl-numericals.test)
(5am:run :sbcl-numericals)
```

You could play from there.

# numericals

After cloning `git clone https://github.com/digikar99/sbcl-numericals.git`

```lisp
(ql:quickload :numericals) ; no tests have been set up
(numericals:+ '(1 2 3) 2)
;=> #(3.0 4.0 5.0)
```

I had been on a break from this project; and have been currently working on "map-outer" that led me to "concatenate", I hope to commit these two today.

**Comment by bpecsek** [comment]
Thank you Shubhamkar!

**Comment by digikar99** [comment]
I have also setup the [test-setup](https://github.com/digikar99/numericals/tree/test-setup) branch. And added a section on [Contributing](https://github.com/digikar99/numericals#todo-contributing) in README. In case you want to contribute, there are non-simd based tasks as well. In fact, once a small amount of SIMD code is added to `numericals.sbcl`, much of the work lies optimizing the code in `numericals.internals` that uses this simd code.

**Comment by digikar99** [comment]
I assume the contribution part, too, has been taken care of. I'm closing this issue; feel free to reopen if required.

For anyone who stumbles upon the discussion, be aware that the project was in (is?) an unstable condition: `test-setup` branch has served its purpose and integrated into the `master`. `numericals.sbcl` was renamed to `numericals/sbcl`. Further changes may have occured since I wrote this comment.
