### ISSUE TITLE
where did you define the function

### ISSUE THREAD

**Issue by anranyicheng** [digikar99/numericals#5]
https://github.com/digikar99/numericals/blob/a8995ea9e976810b74e6910986a66ae16a354f47/src/package.lisp#LL110C1-L110C1

**Comment by digikar99** [comment]
`matmul` hasn't been defined yet; `two-arg-matmul` has been defined in [src/blas.lisp](https://github.com/digikar99/numericals/blob/a8995ea9e976810b74e6910986a66ae16a354f47/src/blas.lisp). 

If you are operating on moderately sized arrays, then you can use [magicl](https://github.com/quil-lang/magicl) itself, or a wrapper around it through `numericals/magicl` or `dense-numericals/magicl`.

If you are using slime/swank, you can `(ql:quickload "polymorphic-functions/swank")` and then `(polymorphic-functions::extend-swank)`.

**Comment by anranyicheng** [comment]
ok, thanks!
